export const NAME_CHANGED = 'name_changed'
export const EMAIL_CHANGED = 'email_changed'
export const USERNAME_CHANGED = 'username_changed'
export const PASSWORD_CHANGED = 'password_changed'
export const LOGIN_USER_SUCCESS = 'login_user_success'
export const LOGIN_USER_FAIL = 'login_user_fail'
export const LOGIN_USER = 'login_user'

export const FETCH_POSTS = 'fetch_posts'
export const CREATE_POST = 'create_post'
export const FETCH_POST = 'fetch_post'
export const DELETE_POST = 'delete_post'

export const AUTH_USER = 'auth_user'  
export const UNAUTH_USER = 'unauth_user'
export const AUTH_ERROR = 'auth_error'
export const FORGOT_PASSWORD_REQUEST = 'forgot_password_request'
export const RESET_PASSWORD_REQUEST = 'reset_password_request'
export const PROTECTED_TEST = 'protected_test'